// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: speech.proto

package speechclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaddleSpeechReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // 文本内容
}

func (x *PaddleSpeechReq) Reset() {
	*x = PaddleSpeechReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speech_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaddleSpeechReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaddleSpeechReq) ProtoMessage() {}

func (x *PaddleSpeechReq) ProtoReflect() protoreflect.Message {
	mi := &file_speech_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaddleSpeechReq.ProtoReflect.Descriptor instead.
func (*PaddleSpeechReq) Descriptor() ([]byte, []int) {
	return file_speech_proto_rawDescGZIP(), []int{0}
}

func (x *PaddleSpeechReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PaddleSpeechReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` //音频保存地址
}

func (x *PaddleSpeechReply) Reset() {
	*x = PaddleSpeechReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speech_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaddleSpeechReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaddleSpeechReply) ProtoMessage() {}

func (x *PaddleSpeechReply) ProtoReflect() protoreflect.Message {
	mi := &file_speech_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaddleSpeechReply.ProtoReflect.Descriptor instead.
func (*PaddleSpeechReply) Descriptor() ([]byte, []int) {
	return file_speech_proto_rawDescGZIP(), []int{1}
}

func (x *PaddleSpeechReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_speech_proto protoreflect.FileDescriptor

var file_speech_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x22, 0x25, 0x0a, 0x0f, 0x50, 0x61, 0x64, 0x64, 0x6c, 0x65,
	0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2d, 0x0a,
	0x11, 0x50, 0x61, 0x64, 0x64, 0x6c, 0x65, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x4e, 0x0a, 0x06,
	0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x12, 0x44, 0x0a, 0x0c, 0x50, 0x61, 0x64, 0x64, 0x6c, 0x65,
	0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x12, 0x17, 0x2e, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x2e,
	0x50, 0x61, 0x64, 0x64, 0x6c, 0x65, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x2e, 0x50, 0x61, 0x64, 0x64, 0x6c, 0x65, 0x53,
	0x70, 0x65, 0x65, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e,
	0x2e, 0x2f, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_speech_proto_rawDescOnce sync.Once
	file_speech_proto_rawDescData = file_speech_proto_rawDesc
)

func file_speech_proto_rawDescGZIP() []byte {
	file_speech_proto_rawDescOnce.Do(func() {
		file_speech_proto_rawDescData = protoimpl.X.CompressGZIP(file_speech_proto_rawDescData)
	})
	return file_speech_proto_rawDescData
}

var file_speech_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_speech_proto_goTypes = []interface{}{
	(*PaddleSpeechReq)(nil),   // 0: speech.PaddleSpeechReq
	(*PaddleSpeechReply)(nil), // 1: speech.PaddleSpeechReply
}
var file_speech_proto_depIdxs = []int32{
	0, // 0: speech.speech.PaddleSpeech:input_type -> speech.PaddleSpeechReq
	1, // 1: speech.speech.PaddleSpeech:output_type -> speech.PaddleSpeechReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_speech_proto_init() }
func file_speech_proto_init() {
	if File_speech_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_speech_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaddleSpeechReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_speech_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaddleSpeechReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_speech_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_speech_proto_goTypes,
		DependencyIndexes: file_speech_proto_depIdxs,
		MessageInfos:      file_speech_proto_msgTypes,
	}.Build()
	File_speech_proto = out.File
	file_speech_proto_rawDesc = nil
	file_speech_proto_goTypes = nil
	file_speech_proto_depIdxs = nil
}
