// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"logic-server/service/download/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pubilc/:FileType/:File",
				Handler: DownloadPublicHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/wav/:File",
				Handler: DownloadWavHandler(serverCtx),
			},
		},
	)
}
